#!/usr/bin/env bash

set -e

ALL_TARGETS=(
    "db-test"
    "parser-test"
)

# Parse command line args
if [ "$#" == 0 ]; then
    TARGETS=("${ALL_TARGETS[@]}")
else
    TARGETS=("${@}")
fi

# Build
ROOT_DIR="$(realpath "$(dirname -- "$0")")"
BUILD_DIR="$ROOT_DIR/build"

mkdir -p "$BUILD_DIR"

cmake \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
    -DCMAKE_BUILD_TYPE=Debug \
    -B "$BUILD_DIR" \
    -S "$ROOT_DIR"

cmake --build "$BUILD_DIR" -- -j4

# Link compile_commands.json
ln -sf "$BUILD_DIR/compile_commands.json" "$ROOT_DIR"

# Run targets
for TARGET in "${TARGETS[@]}"; do
    cmake --build "$BUILD_DIR" --target "$TARGET"
done
