#!/usr/bin/env bash

set -e

ROOT_DIR="$(realpath "$(dirname -- "$0")")"
BUILD_DIR="$ROOT_DIR/build"
TARGETS=(
    "db-test"
    "parser-test"
)

mkdir -p "$BUILD_DIR"

cmake \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=true \
    -DCMAKE_BUILD_TYPE=Debug \
    -B "$BUILD_DIR" \
    -S "$ROOT_DIR"

cmake --build "$BUILD_DIR" -- -j4

ln -sf "$BUILD_DIR/compile_commands.json" "$ROOT_DIR"

for TARGET in "${TARGETS[@]}"; do
    cmake --build "$BUILD_DIR" --target "$TARGET"
done
